### PR TITLE
BSQL Docs -> BSQL Notebooks

### PR DESCRIPTION
**Pull request by gumdropsteve**
Add docs Notebook for BlazingSQL

### CODE REVIEW

**Comment by gumdropsteve** [comment]
#### TBD (file issues after test on newer version)

https://docs.blazingdb.com/docs/queries
- NESTED QUERIES AS NEW COLUMN

https://docs.blazingdb.com/docs/unary-ops
- COTAN
- NOT

**Comment by gumdropsteve** [comment]
@roaramburu ready to merge

**Comment by roaramburu** [comment]
image
Show multi-node multi-gpu as well. use a dask-scheduler IP and port that you make up. I would use localhost `127.0.0.1` and port `8786`

In fact I would make a series of notebooks instead of one long notebook. so one could be basics/fundamentals, one could be distributed, another could be general SQL, and then others based on the major categories of your notebook.

**Comment by roaramburu** [comment]
image
The comments don't match the query type

**Comment by roaramburu** [comment]
image
the style is not consistent. You start using this (idk is this an image?) halfway, and it looks decent, but we need to make the content consistent.

**Comment by roaramburu** [comment]
image
we have to put all the options for storage plugins, not just aws s3 and a mention of minio

**Comment by roaramburu** [comment]
image
we need to have an example for every file type we support so we can link to it. we probably need a header on each to make it linkable

**Pull request merged**
